import { useQuery } from '@tanstack/react-query'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Link } from 'react-router-dom'

import Navbar from '../components/Navbar'
import StatusBadge from '../components/StatusBadge'
import { getIpos } from '../lib/api'
import type { IPOStatus } from '../types/ipo'

export default function Dashboard() {
  const { data: ipos = [], isLoading, isError } = useQuery({ queryKey: ['ipos'], queryFn: () => getIpos() })
  const count = (status: IPOStatus) => ipos.filter((ipo) => ipo.status === status).length
  const chartData = ipos.slice().reverse().map((ipo) => ({ name: ipo.company.name.split(' ')[0], price: (Number(ipo.issue_price_low) + Number(ipo.issue_price_high)) / 2 }))
  const cards = [['Upcoming IPOs', count('Upcoming'), 'text-violet-600 dark:text-violet-300'], ['Open IPOs', count('Open'), 'text-emerald-600 dark:text-emerald-300'], ['Listed IPOs', count('Listed'), 'text-sky-600 dark:text-sky-300'], ['Watchlist', 0, 'text-amber-600 dark:text-amber-300']]
  return <div className="min-h-screen bg-slate-50 dark:bg-slate-950"><Navbar /><main className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-cyan-700 dark:text-cyan-300">Market overview</p><h1 className="mt-2 text-3xl font-black dark:text-white">IPO dashboard</h1><p className="mt-2 text-slate-600 dark:text-slate-300">A live view of IPOs from your research universe.</p></div><Link to="/ipos" className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white dark:bg-cyan-400 dark:text-slate-950">Explore all IPOs</Link></div>
  {isError ? <p className="mt-8 rounded-xl bg-rose-50 p-4 text-rose-700">Unable to load IPO data. Start the backend and try again.</p> : <><section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label, value, color]) => <div key={String(label)} className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-white/10 dark:bg-slate-900"><p className="text-sm text-slate-500">{label}</p><p className={`mt-3 text-3xl font-black ${color}`}>{isLoading ? '—' : value}</p><p className="mt-2 text-xs text-slate-500">Across current IPO coverage</p></div>)}</section>
  <section className="mt-8 grid gap-6 lg:grid-cols-5"><div className="rounded-2xl border border-slate-200 bg-white p-6 lg:col-span-3 dark:border-white/10 dark:bg-slate-900"><h2 className="font-bold dark:text-white">Issue price trend</h2><p className="mt-1 text-sm text-slate-500">Midpoint of IPO price bands</p><div className="mt-6 h-64">{chartData.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="priceFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#06b6d4" stopOpacity={.35}/><stop offset="100%" stopColor="#06b6d4" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#94a3b833"/><XAxis dataKey="name" tickLine={false} axisLine={false} fontSize={12}/><YAxis tickLine={false} axisLine={false} fontSize={12}/><Tooltip /><Area type="monotone" dataKey="price" stroke="#0891b2" strokeWidth={3} fill="url(#priceFill)" /></AreaChart></ResponsiveContainer> : <div className="grid h-full place-items-center text-slate-500">Loading chart…</div>}</div></div><div className="rounded-2xl border border-slate-200 bg-gradient-to-br from-slate-950 to-slate-800 p-6 text-white lg:col-span-2"><p className="text-sm text-cyan-300">Research focus</p><h2 className="mt-2 text-2xl font-bold">Understand demand before the listing day.</h2><p className="mt-4 text-sm leading-6 text-slate-300">Compare price bands, subscription levels, GMP, and key dates in one research view.</p><Link to="/ipos" className="mt-7 inline-block rounded-lg bg-cyan-400 px-4 py-2.5 text-sm font-bold text-slate-950">Review IPOs →</Link></div></section>
  <section className="mt-8 rounded-2xl border border-slate-200 bg-white p-6 dark:border-white/10 dark:bg-slate-900"><div className="flex items-center justify-between"><div><h2 className="font-bold dark:text-white">Recent IPOs</h2><p className="mt-1 text-sm text-slate-500">Latest openings and listings in the platform.</p></div><Link to="/ipos" className="text-sm font-bold text-cyan-700 dark:text-cyan-300">View all</Link></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-b border-slate-100 text-xs uppercase tracking-wider text-slate-500 dark:border-white/10"><tr><th className="pb-3">Company</th><th className="pb-3">Price band</th><th className="pb-3">Open date</th><th className="pb-3">Status</th></tr></thead><tbody>{ipos.slice(0, 5).map((ipo) => <tr key={ipo.id} className="border-b border-slate-100 last:border-0 dark:border-white/10"><td className="py-4"><Link to={`/ipo/${ipo.id}`} className="font-semibold hover:text-cyan-600 dark:text-white">{ipo.company.name}</Link><p className="text-xs text-slate-500">{ipo.company.industry}</p></td><td className="py-4 dark:text-slate-200">₹{ipo.issue_price_low}–{ipo.issue_price_high}</td><td className="py-4 text-slate-600 dark:text-slate-300">{new Date(ipo.open_date).toLocaleDateString('en-IN')}</td><td className="py-4"><StatusBadge status={ipo.status}/></td></tr>)}</tbody></table></div></section></>}</main></div>
}
